DROP INDEX IF EXISTS idx_dm_users;
DROP INDEX IF EXISTS idx_dm_created_at;

CREATE INDEX IF NOT EXISTS idx_dm_sender_receiver
    ON direct_messages(sender_id, receiver_id, dm_created_at DESC)
    WHERE dm_deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_dm_receiver_sender
    ON direct_messages(receiver_id, sender_id, dm_created_at DESC)
    WHERE dm_deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_groups_active
    ON groups(group_id)
    WHERE group_deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS conversations(
    conversation_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    conversation_type INT NOT NULL CHECK(conversation_type IN (1,2)),
    reference_id INT NOT NULL, -- group_id hoặc tự generate cho DM
    last_message_id INT DEFAULT NULL,
    last_message_at TIMESTAMPTZ DEFAULT NULL,
    conversation_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    conversation_updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON COLUMN conversations.conversation_type IS '1:DM - 2:Group';
COMMENT ON COLUMN conversations.reference_id IS 'It is group_id or create new ID if it is new converstation';

CREATE OR REPLACE FUNCTION update_converstation_update_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.conversation_updated_at=now();
    return NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_converstation_update_at
BEFORE UPDATE ON conversations
FOR EACH ROW
EXECUTE FUNCTION update_converstation_update_at();

CREATE TABLE IF NOT EXISTS conversation_participants(
    participant_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id INT NOT NULL,
    user_id INT NOT NULL,
    last_read_message_id INT DEFAULT NULL,
    last_read_at TIMESTAMPTZ DEFAULT NULL,
    is_muted BOOLEAN DEFAULT FALSE,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    left_at TIMESTAMPTZ DEFAULT NULL,
    CONSTRAINT fk_conversation FOREIGN KEY(conversation_id) REFERENCES conversations(conversation_id),
    CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(user_id),
    UNIQUE(conversation_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_conv_participants_user
    ON conversation_participants(user_id)
    WHERE left_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_conv_participants_conv
    ON conversation_participants(conversation_id)
    WHERE left_at IS NULL;
