CREATE TABLE IF NOT EXISTS groups(
    group_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    group_name VARCHAR(150) NOT NULL,
    group_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    group_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    group_deleted_at TIMESTAMPTZ DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS group_members(
    group_member_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INT NOT NULL,
    user_id INT NOT NULL,
    member_role INT NOT NULL DEFAULT 1 CHECK(member_role IN (1,2,3)),
    jointed_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    left_at TIMESTAMPTZ DEFAULT NULL,
    CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(user_id),
    CONSTRAINT fk_group FOREIGN KEY(group_id) REFERENCES groups(group_id)
);
CREATE TABLE IF NOT EXISTS messages(
    message_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id INT NOT NULL,
    group_id INT NOT NULL,
    message_content TEXT NOT NULL,
    attachments JSONB DEFAULT NULL,
    message_type INT NOT NULL DEFAULT 1 CHECK(message_type IN (1,2,3)),
    reply_to INT DEFAULT NULL,
    message_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    message_deleted_at TIMESTAMPTZ DEFAULT NULL,
    CONSTRAINT fk_user FOREIGN KEY(sender_id) REFERENCES users(user_id),
    CONSTRAINT fk_group FOREIGN KEY(group_id) REFERENCES groups(group_id)
);
CREATE TABLE IF NOT EXISTS direct_messages(
    dm_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id INT NOT NULL,
    receiver_id INT NOT NULL,
    dm_content TEXT NOT NULL,
    dm_attachments JSONB DEFAULT NULL,
    dm_message_type INT DEFAULT 1 CHECK(dm_message_type IN (1,2,3)),
    dm_read_at TIMESTAMPTZ DEFAULT NULL,
    dm_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    dm_deleted_at TIMESTAMPTZ DEFAULT NULL,
    CONSTRAINT fk_sender FOREIGN KEY(sender_id) REFERENCES users(user_id),
    CONSTRAINT fk_receiver FOREIGN KEY(receiver_id) REFERENCES users(user_id)
);
-- Create comments
COMMENT ON COLUMN group_members.member_role IS '1:Member Role - 2:Moderator Role - 3:Adminstator Role';
COMMENT ON COLUMN messages.message_type IS '1:Text - 2:Image - 3:File';
COMMENT ON COLUMN direct_messages.dm_message_type IS '1:Text - 2:Image - 3:File';
-- Create Message Table Index
CREATE INDEX IF NOT EXISTS idx_messages_group_id ON messages(group_id);
CREATE INDEX IF NOT EXISTS idx_messages_sender_id ON messages(sender_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages(message_created_at DESC);
-- Create Group members table index
CREATE INDEX IF NOT EXISTS idx_group_members_user_id ON group_members(user_id);
CREATE INDEX IF NOT EXISTS idx_group_members_left_at ON group_members(left_at);
-- Create Direct message table index
CREATE INDEX IF NOT EXISTS idx_dm_users ON direct_messages(sender_id,receiver_id);
CREATE INDEX IF NOT EXISTS idx_dm_created_at ON direct_messages(dm_created_at);

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.group_updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_groups_update_at
BEFORE UPDATE ON groups
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
