// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const editMessage = `-- name: EditMessage :one
UPDATE messages
SET
    message_content = $1
WHERE
    group_id = (SELECT group_id FROM groups WHERE group_uuid = $2::UUID)
    AND sender_id = (SELECT user_id FROM users WHERE user_uuid = $3::UUID)
    AND EXISTS(
        SELECT 1
        FROM group_members gm
        INNER JOIN groups g ON g.group_id = gm.group_id
        INNER JOIN users u ON u.user_id = sender_id
        WHERE
            gm.left_at IS NULL
    )
RETURNING message_id, sender_id, message_content, attachments, message_type, reply_to, message_created_at, message_deleted_at, conversation_id
`

type EditMessageParams struct {
	MessageContent string    `json:"message_content"`
	GroupUuid      uuid.UUID `json:"group_uuid"`
	UserUuid       uuid.UUID `json:"user_uuid"`
}

func (q *Queries) EditMessage(ctx context.Context, arg EditMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, editMessage, arg.MessageContent, arg.GroupUuid, arg.UserUuid)
	var i Message
	err := row.Scan(
		&i.MessageID,
		&i.SenderID,
		&i.MessageContent,
		&i.Attachments,
		&i.MessageType,
		&i.ReplyTo,
		&i.MessageCreatedAt,
		&i.MessageDeletedAt,
		&i.ConversationID,
	)
	return i, err
}

const getMessages = `-- name: GetMessages :many
SELECT m.message_id, m.sender_id, m.message_content, m.attachments,
       m.message_type, m.reply_to, m.message_created_at
FROM messages m
WHERE m.conversation_id = $1::INT
  AND m.message_deleted_at IS NULL
  AND ($2::timestamptz IS NULL
       OR (m.message_created_at, m.message_id) < ($2::timestamptz, $3::int))
ORDER BY m.message_created_at DESC, m.message_id DESC
LIMIT $4::INT
`

type GetMessagesParams struct {
	ConversationID int32              `json:"conversation_id"`
	CursorTime     pgtype.Timestamptz `json:"cursor_time"`
	CursorID       *int32             `json:"cursor_id"`
	Limitarg       int32              `json:"limitarg"`
}

type GetMessagesRow struct {
	MessageID        int32     `json:"message_id"`
	SenderID         int32     `json:"sender_id"`
	MessageContent   string    `json:"message_content"`
	Attachments      []byte    `json:"attachments"`
	MessageType      int32     `json:"message_type"`
	ReplyTo          *int32    `json:"reply_to"`
	MessageCreatedAt time.Time `json:"message_created_at"`
}

func (q *Queries) GetMessages(ctx context.Context, arg GetMessagesParams) ([]GetMessagesRow, error) {
	rows, err := q.db.Query(ctx, getMessages,
		arg.ConversationID,
		arg.CursorTime,
		arg.CursorID,
		arg.Limitarg,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMessagesRow{}
	for rows.Next() {
		var i GetMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.SenderID,
			&i.MessageContent,
			&i.Attachments,
			&i.MessageType,
			&i.ReplyTo,
			&i.MessageCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMessageInGroup = `-- name: SearchMessageInGroup :many
SELECT
    u.user_uuid,
    ms.message_content,
    ms.attachments,
    ms.message_type,
    ms.reply_to,
    ms.message_created_at
FROM messages ms
INNER JOIN groups g ON g.group_id = ms.group_id
INNER JOIN users u ON u.user_id = ms.sender_id
WHERE
    g.group_uuid = $1::UUID
    AND EXISTS (
        SELECT 1 FROM group_members gm
        WHERE gm.group_id = g.group_id
            AND gm.member_id = u.user_id
            AND gm.left_at IS NULL
    )
    AND to_tsvector('english', COALESCE(ms.message_content, '')) @@
        plainto_tsquery('english', $2::TEXT)
ORDER BY ms.message_created_at DESC
LIMIT $4 OFFSET $3
`

type SearchMessageInGroupParams struct {
	GroupUuid uuid.UUID `json:"group_uuid"`
	Search    string    `json:"search"`
	Offsetarg int32     `json:"offsetarg"`
	Limitarg  int32     `json:"limitarg"`
}

type SearchMessageInGroupRow struct {
	UserUuid         uuid.UUID `json:"user_uuid"`
	MessageContent   string    `json:"message_content"`
	Attachments      []byte    `json:"attachments"`
	MessageType      int32     `json:"message_type"`
	ReplyTo          *int32    `json:"reply_to"`
	MessageCreatedAt time.Time `json:"message_created_at"`
}

func (q *Queries) SearchMessageInGroup(ctx context.Context, arg SearchMessageInGroupParams) ([]SearchMessageInGroupRow, error) {
	rows, err := q.db.Query(ctx, searchMessageInGroup,
		arg.GroupUuid,
		arg.Search,
		arg.Offsetarg,
		arg.Limitarg,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMessageInGroupRow{}
	for rows.Next() {
		var i SearchMessageInGroupRow
		if err := rows.Scan(
			&i.UserUuid,
			&i.MessageContent,
			&i.Attachments,
			&i.MessageType,
			&i.ReplyTo,
			&i.MessageCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sendMessage = `-- name: SendMessage :one
WITH sender AS(
    SELECT user_id FROM users WHERE user_uuid = $2::UUID
),
conv AS(
    SELECT conversation_id
        FROM conversations
        WHERE conversation_id = $1::INT
            AND EXISTS(
                SELECT 1 FROM conversation_participants
                WHERE conversation_id = $1::INT
                    AND user_id = (SELECT user_id FROM sender)
                    AND left_at IS NULL
            )
),
new_msg AS(
    INSERT INTO messages (conversation_id, sender_id, message_content, attachments, message_type, reply_to)
    SELECT
        c.conversation_id,s.user_id, $3::TEXT,
        COALESCE($4::JSONB,'[]'::JSONB),
        $5::INT,
        $6::INT
    FROM conv c, sender s
    WHERE EXISTS (SELECT 1 FROM conv)
    RETURNING message_id, sender_id, message_content, attachments, message_type, reply_to, message_created_at, message_deleted_at, conversation_id
)
UPDATE conversations
SET
    last_message_id = (SELECT message_id FROM new_msg),
    last_message_at = (SELECT message_created_at FROM new_msg),
    conversation_updated_at = now()
WHERE conversation_id = $1::INT
    AND EXISTS (SELECT 1 FROM new_msg)
RETURNING (SELECT message_id FROM new_msg) AS message_id
`

type SendMessageParams struct {
	ConversationID int32           `json:"conversation_id"`
	UserUuid       uuid.UUID       `json:"user_uuid"`
	Content        string          `json:"content"`
	Attachments    json.RawMessage `json:"attachments"`
	MessageType    int32           `json:"message_type"`
	ReplyTo        int32           `json:"reply_to"`
}

func (q *Queries) SendMessage(ctx context.Context, arg SendMessageParams) (int32, error) {
	row := q.db.QueryRow(ctx, sendMessage,
		arg.ConversationID,
		arg.UserUuid,
		arg.Content,
		arg.Attachments,
		arg.MessageType,
		arg.ReplyTo,
	)
	var message_id int32
	err := row.Scan(&message_id)
	return message_id, err
}

const softDeleteMessage = `-- name: SoftDeleteMessage :one
UPDATE messages
SET message_deleted_at = now()
WHERE message_id = $1::INT
  AND sender_id = (SELECT user_id FROM users WHERE user_uuid = $2::UUID)
  AND group_id = (SELECT group_id FROM groups WHERE group_uuid = $3::UUID)
  AND EXISTS (
      SELECT 1 FROM group_members gm
      WHERE gm.group_id = messages.group_id
        AND gm.member_id = messages.sender_id
        AND gm.left_at IS NULL
  )
RETURNING message_id, sender_id, message_content, attachments, message_type, reply_to, message_created_at, message_deleted_at, conversation_id
`

type SoftDeleteMessageParams struct {
	MessageID int32     `json:"message_id"`
	UserUuid  uuid.UUID `json:"user_uuid"`
	GroupUuid uuid.UUID `json:"group_uuid"`
}

func (q *Queries) SoftDeleteMessage(ctx context.Context, arg SoftDeleteMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, softDeleteMessage, arg.MessageID, arg.UserUuid, arg.GroupUuid)
	var i Message
	err := row.Scan(
		&i.MessageID,
		&i.SenderID,
		&i.MessageContent,
		&i.Attachments,
		&i.MessageType,
		&i.ReplyTo,
		&i.MessageCreatedAt,
		&i.MessageDeletedAt,
		&i.ConversationID,
	)
	return i, err
}

const validateReply = `-- name: ValidateReply :one
SELECT EXISTS(
    SELECT 1 FROM messages
    WHERE message_id = $1::int
      AND conversation_id = $2::int
      AND message_deleted_at IS NULL
)::boolean
`

type ValidateReplyParams struct {
	MessageID      int32 `json:"message_id"`
	ConversationID int32 `json:"conversation_id"`
}

func (q *Queries) ValidateReply(ctx context.Context, arg ValidateReplyParams) (bool, error) {
	row := q.db.QueryRow(ctx, validateReply, arg.MessageID, arg.ConversationID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
