// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addParticipantToConversation = `-- name: AddParticipantToConversation :exec
INSERT INTO conversation_participants (conversation_id, user_id)
VALUES ($1, $2)
ON CONFLICT (conversation_id, user_id) WHERE left_at IS NULL DO NOTHING
`

type AddParticipantToConversationParams struct {
	ConversationID int32 `json:"conversation_id"`
	UserID         int32 `json:"user_id"`
}

func (q *Queries) AddParticipantToConversation(ctx context.Context, arg AddParticipantToConversationParams) error {
	_, err := q.db.Exec(ctx, addParticipantToConversation, arg.ConversationID, arg.UserID)
	return err
}

const createDMConversation = `-- name: CreateDMConversation :one
INSERT INTO conversations (conversation_type, reference_id)
VALUES (1, nextval('dm_reference_seq'))
RETURNING conversation_id
`

func (q *Queries) CreateDMConversation(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, createDMConversation)
	var conversation_id int32
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const findDMConversation = `-- name: FindDMConversation :one
SELECT c.conversation_id
FROM conversations c
WHERE c.conversation_type = 1
  AND EXISTS (
    SELECT 1 FROM conversation_participants cp
    WHERE cp.conversation_id = c.conversation_id AND cp.user_id = $1
  )
  AND EXISTS (
    SELECT 1 FROM conversation_participants cp
    WHERE cp.conversation_id = c.conversation_id AND cp.user_id = $2
  )
LIMIT 1
`

type FindDMConversationParams struct {
	User1ID int32 `json:"user1_id"`
	User2ID int32 `json:"user2_id"`
}

func (q *Queries) FindDMConversation(ctx context.Context, arg FindDMConversationParams) (int32, error) {
	row := q.db.QueryRow(ctx, findDMConversation, arg.User1ID, arg.User2ID)
	var conversation_id int32
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const getDMConversation = `-- name: GetDMConversation :many
SELECT
    c.conversation_id,
    1 AS conversation_type,
    u.user_email,
    c.last_message_id,
    c.last_message_at,
    (
        SELECT COUNT(*)
        FROM messages m
        WHERE m.conversation_id = c.conversation_id
            AND m.message_id > COALESCE(
                (SELECT last_read_message_id FROM conversation_participants
                    WHERE conversation_id = c.conversation_id AND user_id = $1::INT)
            ,0)
            AND m.message_deleted_at IS NULL
    ) AS unread_count
FROM conversations c
JOIN conversation_participants cp ON c.conversation_id = cp.conversation_id AND cp.user_id <> $1::INT
JOIN users u ON cp.user_id = u.user_id
WHERE c.conversation_type = 1
    AND EXISTS
        (
            SELECT 1 FROM conversation_participants
            WHERE conversation_id = c.conversation_id
                AND user_id = $1::INT
                AND left_at IS NULL
        )
ORDER BY c.last_message_at DESC NULLS LAST
`

type GetDMConversationRow struct {
	ConversationID   int32              `json:"conversation_id"`
	ConversationType int32              `json:"conversation_type"`
	UserEmail        string             `json:"user_email"`
	LastMessageID    *int32             `json:"last_message_id"`
	LastMessageAt    pgtype.Timestamptz `json:"last_message_at"`
	UnreadCount      int64              `json:"unread_count"`
}

func (q *Queries) GetDMConversation(ctx context.Context, curUserID int32) ([]GetDMConversationRow, error) {
	rows, err := q.db.Query(ctx, getDMConversation, curUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDMConversationRow{}
	for rows.Next() {
		var i GetDMConversationRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.ConversationType,
			&i.UserEmail,
			&i.LastMessageID,
			&i.LastMessageAt,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupConversation = `-- name: GetGroupConversation :many
SELECT
    c.conversation_id,
    2 AS conversation_type,
    g.group_name AS title,
    c.last_message_id,
    c.last_message_at,
    (
        SELECT COUNT(*)
        FROM messages m
        WHERE m.conversation_id = c.conversation_id
            AND m.message_id > COALESCE(
                (SELECT last_read_message_id FROM conversation_participants
                    WHERE conversation_id = c.conversation_id AND user_id = $1::INT)
            ,0)
            AND m.message_deleted_at IS NULL
    ) AS unread_count
FROM conversations c
JOIN groups g ON c.reference_id = g.group_id
WHERE c.conversation_type = 2
    AND EXISTS (
        SELECT 1 FROM conversation_participants
        WHERE conversation_id = c.conversation_id
            AND user_id = $1
            AND left_at IS NULL
    )
ORDER BY c.last_message_at DESC NULLS LAST
`

type GetGroupConversationRow struct {
	ConversationID   int32              `json:"conversation_id"`
	ConversationType int32              `json:"conversation_type"`
	Title            string             `json:"title"`
	LastMessageID    *int32             `json:"last_message_id"`
	LastMessageAt    pgtype.Timestamptz `json:"last_message_at"`
	UnreadCount      int64              `json:"unread_count"`
}

func (q *Queries) GetGroupConversation(ctx context.Context, curUserID int32) ([]GetGroupConversationRow, error) {
	rows, err := q.db.Query(ctx, getGroupConversation, curUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupConversationRow{}
	for rows.Next() {
		var i GetGroupConversationRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.ConversationType,
			&i.Title,
			&i.LastMessageID,
			&i.LastMessageAt,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteConversation = `-- name: HardDeleteConversation :exec
DELETE FROM conversations
WHERE conversation_type = 2
    AND reference_id = (SELECT group_id FROM groups WHERE group_uuid = $1)
`

func (q *Queries) HardDeleteConversation(ctx context.Context, groupUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteConversation, groupUuid)
	return err
}

const leaveConversation = `-- name: LeaveConversation :exec
UPDATE conversation_participants
SET left_at = now()
WHERE conversation_id = $1::int
    AND user_id = (SELECT user_id FROM users WHERE user_uuid = $2::UUID)
    AND left_at IS NULL
`

type LeaveConversationParams struct {
	ConversationID int32     `json:"conversation_id"`
	UserUuid       uuid.UUID `json:"user_uuid"`
}

func (q *Queries) LeaveConversation(ctx context.Context, arg LeaveConversationParams) error {
	_, err := q.db.Exec(ctx, leaveConversation, arg.ConversationID, arg.UserUuid)
	return err
}
