// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: direct_messages.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const editDirectMessage = `-- name: EditDirectMessage :one
UPDATE direct_messages
SET
    dm_content = $1
WHERE dm_id = $2
    AND sender_id = (SELECT user_id FROM users WHERE user_uuid = $3::UUID)
    AND dm.dm_deleted_at IS NULL
    AND dm.dm_read_at IS NULL
    AND dm_message_type = 1
RETURNING dm_id, sender_id, receiver_id, dm_content, dm_attachments, dm_message_type, dm_read_at, dm_created_at, dm_deleted_at
`

type EditDirectMessageParams struct {
	DmContent       string    `json:"dm_content"`
	DmID            int32     `json:"dm_id"`
	CurrentUserUuid uuid.UUID `json:"current_user_uuid"`
}

func (q *Queries) EditDirectMessage(ctx context.Context, arg EditDirectMessageParams) (DirectMessage, error) {
	row := q.db.QueryRow(ctx, editDirectMessage, arg.DmContent, arg.DmID, arg.CurrentUserUuid)
	var i DirectMessage
	err := row.Scan(
		&i.DmID,
		&i.SenderID,
		&i.ReceiverID,
		&i.DmContent,
		&i.DmAttachments,
		&i.DmMessageType,
		&i.DmReadAt,
		&i.DmCreatedAt,
		&i.DmDeletedAt,
	)
	return i, err
}

const getDirectMessageWithUser = `-- name: GetDirectMessageWithUser :many
WITH user_ids AS(
    SELECT
        u.user_id AS current_user_id,
        ou.user_id AS other_user_id
    FROM users u, users ou
    WHERE
        u.user_uuid = $3::UUID
        AND ou.user_uuid = $4::UUID
)
SELECT
    dm.dm_id,
    CASE
        WHEN dm.sender_id = uid.current_user_id THEN TRUE ELSE FALSE
    END AS is_mine,
    dm.dm_content,
    dm.dm_attachments,
    dm.dm_message_type,
    dm.dm_read_at,
    dm.dm_created_at
FROM direct_messages dm
JOIN user_ids uid
    ON (dm.sender_id = uid.current_user_id AND dm.receiver_id = uid.other_user_id)
    OR (dm.sender_id = uid.other_user_id AND dm.receiver_id = uid.current_user_id)
WHERE dm.dm_deleted_at IS NULL
ORDER BY dm.dm_created_at DESC
LIMIT $2 OFFSET $1
`

type GetDirectMessageWithUserParams struct {
	Offsetarg       int32     `json:"offsetarg"`
	Limitarg        int32     `json:"limitarg"`
	CurrentUserUuid uuid.UUID `json:"current_user_uuid"`
	OtherUserUuid   uuid.UUID `json:"other_user_uuid"`
}

type GetDirectMessageWithUserRow struct {
	DmID          int32              `json:"dm_id"`
	IsMine        bool               `json:"is_mine"`
	DmContent     string             `json:"dm_content"`
	DmAttachments []byte             `json:"dm_attachments"`
	DmMessageType *int32             `json:"dm_message_type"`
	DmReadAt      pgtype.Timestamptz `json:"dm_read_at"`
	DmCreatedAt   time.Time          `json:"dm_created_at"`
}

func (q *Queries) GetDirectMessageWithUser(ctx context.Context, arg GetDirectMessageWithUserParams) ([]GetDirectMessageWithUserRow, error) {
	rows, err := q.db.Query(ctx, getDirectMessageWithUser,
		arg.Offsetarg,
		arg.Limitarg,
		arg.CurrentUserUuid,
		arg.OtherUserUuid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDirectMessageWithUserRow{}
	for rows.Next() {
		var i GetDirectMessageWithUserRow
		if err := rows.Scan(
			&i.DmID,
			&i.IsMine,
			&i.DmContent,
			&i.DmAttachments,
			&i.DmMessageType,
			&i.DmReadAt,
			&i.DmCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDirectMessagesConversations = `-- name: GetDirectMessagesConversations :many
WITH cur_user AS (
    SELECT user_id FROM users WHERE user_uuid = $3::UUID
)
SELECT
    c.conversation_id,
    c.last_message_at,
    other_user.user_uuid AS other_user_uuid,
    other_user.user_email as other_user_email,
    dm.dm_content AS last_message_content,
    dm.dm_message_type AS last_message_type,
    (
        SELECT count(*)
        FROM direct_messages dm2
        WHERE dm2.receiver_id = (SELECT user_id FROM cur_user)
            AND dm2.sender_id = other_user.user_id
            AND (cp.last_read_message_id IS NULL OR dm2.dm_id > cp.last_read_message_id)
            AND dm2.dm_deleted_at IS NULL
    ) AS unread_count
FROM conversations c
JOIN conversation_participants cp
    ON cp.conversation_id = c.conversation_id
    AND cp.user_id = (SELECT user_id FROM cur_user)
    AND cp.left_at IS NULL
JOIN conversation_participants cp_other
    ON cp_other.conversation_id = c.conversation_id
    AND cp_other.user_id != (SELECT user_id FROM current_user)
    AND cp_other.left_at IS NULL
JOIN users other_user
    ON other_user.user_id = cp_other.user_id
LEFT JOIN direct_messages dm
    ON dm.dm_id = c.last_message_id
    AND dm.dm_deleted_at IS NULL
WHERE c.conversation_type = 1
ORDER BY c.last_message_at DESC NULLS LAST
LIMIT $2 OFFSET $1
`

type GetDirectMessagesConversationsParams struct {
	Offsetarg int32     `json:"offsetarg"`
	Limitarg  int32     `json:"limitarg"`
	UserUuid  uuid.UUID `json:"user_uuid"`
}

type GetDirectMessagesConversationsRow struct {
	ConversationID     int32              `json:"conversation_id"`
	LastMessageAt      pgtype.Timestamptz `json:"last_message_at"`
	OtherUserUuid      uuid.UUID          `json:"other_user_uuid"`
	OtherUserEmail     string             `json:"other_user_email"`
	LastMessageContent string             `json:"last_message_content"`
	LastMessageType    *int32             `json:"last_message_type"`
	UnreadCount        int64              `json:"unread_count"`
}

func (q *Queries) GetDirectMessagesConversations(ctx context.Context, arg GetDirectMessagesConversationsParams) ([]GetDirectMessagesConversationsRow, error) {
	rows, err := q.db.Query(ctx, getDirectMessagesConversations, arg.Offsetarg, arg.Limitarg, arg.UserUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDirectMessagesConversationsRow{}
	for rows.Next() {
		var i GetDirectMessagesConversationsRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.LastMessageAt,
			&i.OtherUserUuid,
			&i.OtherUserEmail,
			&i.LastMessageContent,
			&i.LastMessageType,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadDM = `-- name: GetUnreadDM :one
WITH unread_msgs AS (
    SELECT dm_id, sender_id
    FROM direct_messages
    WHERE receiver_id = (SELECT user_id FROM users WHERE user_uuid = $1::UUID)
      AND dm_deleted_at IS NULL
      AND dm_read_at IS NULL
),
total AS (
    SELECT COUNT(*) AS total_unread FROM unread_msgs
),
by_user AS (
    SELECT COALESCE(
        jsonb_agg(jsonb_build_object('user_id', sender_id, 'count', c) ORDER BY user_id),
        '[]'::jsonb
    ) AS unread_by_user
    FROM (
        SELECT sender_id AS user_id, COUNT(*) AS c
        FROM unread_msgs
        GROUP BY sender_id
    ) t
)
SELECT total.total_unread, by_user.unread_by_user
FROM total, by_user
`

type GetUnreadDMRow struct {
	TotalUnread  int64       `json:"total_unread"`
	UnreadByUser interface{} `json:"unread_by_user"`
}

func (q *Queries) GetUnreadDM(ctx context.Context, currentUserUuid uuid.UUID) (GetUnreadDMRow, error) {
	row := q.db.QueryRow(ctx, getUnreadDM, currentUserUuid)
	var i GetUnreadDMRow
	err := row.Scan(&i.TotalUnread, &i.UnreadByUser)
	return i, err
}

const readAllDirectMessages = `-- name: ReadAllDirectMessages :one
WITH updated AS (
    UPDATE direct_messages
    SET dm_read_at = now()
    WHERE sender_id = (SELECT user_id FROM users WHERE user_uuid = $1::UUID)
      AND receiver_id = (SELECT user_id FROM users WHERE user_uuid = $2::UUID)
      AND dm_deleted_at IS NULL
      AND dm_read_at IS NULL
    RETURNING dm_id
)
SELECT count(*) AS read_count FROM updated
`

type ReadAllDirectMessagesParams struct {
	ReceiverUuid    uuid.UUID `json:"receiver_uuid"`
	CurrentUserUuid uuid.UUID `json:"current_user_uuid"`
}

func (q *Queries) ReadAllDirectMessages(ctx context.Context, arg ReadAllDirectMessagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, readAllDirectMessages, arg.ReceiverUuid, arg.CurrentUserUuid)
	var read_count int64
	err := row.Scan(&read_count)
	return read_count, err
}

const readDirectMessage = `-- name: ReadDirectMessage :one
UPDATE direct_messages
SET
    dm_read_at = now()
WHERE dm_id = $1
    AND receiver_id = (SELECT user_id FROM users WHERE user_uuid = $2::UUID)
    AND dm.dm_deleted_at IS NULL
    AND dm.dm_read_at IS NULL
RETURNING dm_id, sender_id, receiver_id, dm_content, dm_attachments, dm_message_type, dm_read_at, dm_created_at, dm_deleted_at
`

type ReadDirectMessageParams struct {
	DmID            int32     `json:"dm_id"`
	CurrentUserUuid uuid.UUID `json:"current_user_uuid"`
}

func (q *Queries) ReadDirectMessage(ctx context.Context, arg ReadDirectMessageParams) (DirectMessage, error) {
	row := q.db.QueryRow(ctx, readDirectMessage, arg.DmID, arg.CurrentUserUuid)
	var i DirectMessage
	err := row.Scan(
		&i.DmID,
		&i.SenderID,
		&i.ReceiverID,
		&i.DmContent,
		&i.DmAttachments,
		&i.DmMessageType,
		&i.DmReadAt,
		&i.DmCreatedAt,
		&i.DmDeletedAt,
	)
	return i, err
}

const searchDirectMessagesWithUser = `-- name: SearchDirectMessagesWithUser :many
WITH user_ids AS (
    SELECT
        cu.user_id AS current_user_id,
        ou.user_id AS other_user_id
    FROM users cu, users ou
    WHERE cu.user_uuid = $2::UUID
      AND ou.user_uuid = $3::UUID
)
SELECT
    dm.dm_id,
    dm.sender_id,
    dm.receiver_id,
    dm.dm_content,
    dm.dm_attachments,
    dm.dm_message_type,
    dm.dm_read_at,
    dm.dm_created_at
FROM direct_messages dm
JOIN user_ids uid
    ON (dm.sender_id = uid.current_user_id AND dm.receiver_id = uid.other_user_id)
    OR (dm.sender_id = uid.other_user_id AND dm.receiver_id = uid.current_user_id)
WHERE dm.dm_content ILIKE '%' || $1 || '%'
  AND dm.dm_deleted_at IS NULL
`

type SearchDirectMessagesWithUserParams struct {
	Search          string    `json:"search"`
	CurrentUserUuid uuid.UUID `json:"current_user_uuid"`
	OtherUserUuid   uuid.UUID `json:"other_user_uuid"`
}

type SearchDirectMessagesWithUserRow struct {
	DmID          int32              `json:"dm_id"`
	SenderID      int32              `json:"sender_id"`
	ReceiverID    int32              `json:"receiver_id"`
	DmContent     string             `json:"dm_content"`
	DmAttachments []byte             `json:"dm_attachments"`
	DmMessageType *int32             `json:"dm_message_type"`
	DmReadAt      pgtype.Timestamptz `json:"dm_read_at"`
	DmCreatedAt   time.Time          `json:"dm_created_at"`
}

func (q *Queries) SearchDirectMessagesWithUser(ctx context.Context, arg SearchDirectMessagesWithUserParams) ([]SearchDirectMessagesWithUserRow, error) {
	rows, err := q.db.Query(ctx, searchDirectMessagesWithUser, arg.Search, arg.CurrentUserUuid, arg.OtherUserUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDirectMessagesWithUserRow{}
	for rows.Next() {
		var i SearchDirectMessagesWithUserRow
		if err := rows.Scan(
			&i.DmID,
			&i.SenderID,
			&i.ReceiverID,
			&i.DmContent,
			&i.DmAttachments,
			&i.DmMessageType,
			&i.DmReadAt,
			&i.DmCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sentDirectMessages = `-- name: SentDirectMessages :one
INSERT INTO direct_messages(sender_id, receiver_id, dm_content, dm_attachments, dm_message_type)
SELECT
    u.user_id,
    ou.user_id,
    $1::TEXT,
    $2::JSONB,
    COALESCE($3::INT, 1)
FROM users u, users ou
WHERE u.user_uuid = $4::UUID
  AND ou.user_uuid = $5::UUID
RETURNING dm_id, sender_id, receiver_id, dm_content, dm_attachments, dm_message_type, dm_read_at, dm_created_at, dm_deleted_at
`

type SentDirectMessagesParams struct {
	DmContent       string          `json:"dm_content"`
	DmAttachments   json.RawMessage `json:"dm_attachments"`
	DmMessageType   int32           `json:"dm_message_type"`
	CurrentUserUuid uuid.UUID       `json:"current_user_uuid"`
	OtherUserUuid   uuid.UUID       `json:"other_user_uuid"`
}

func (q *Queries) SentDirectMessages(ctx context.Context, arg SentDirectMessagesParams) (DirectMessage, error) {
	row := q.db.QueryRow(ctx, sentDirectMessages,
		arg.DmContent,
		arg.DmAttachments,
		arg.DmMessageType,
		arg.CurrentUserUuid,
		arg.OtherUserUuid,
	)
	var i DirectMessage
	err := row.Scan(
		&i.DmID,
		&i.SenderID,
		&i.ReceiverID,
		&i.DmContent,
		&i.DmAttachments,
		&i.DmMessageType,
		&i.DmReadAt,
		&i.DmCreatedAt,
		&i.DmDeletedAt,
	)
	return i, err
}

const softDeleteDirectMessage = `-- name: SoftDeleteDirectMessage :one
UPDATE direct_messages
SET
    dm_deleted_at = now()
WHERE dm_id = $1
    AND sender_id = (SELECT user_id FROM users WHERE user_uuid = $2::UUID)
    AND dm.dm_deleted_at IS NULL
RETURNING dm_id, sender_id, receiver_id, dm_content, dm_attachments, dm_message_type, dm_read_at, dm_created_at, dm_deleted_at
`

type SoftDeleteDirectMessageParams struct {
	DmID            int32     `json:"dm_id"`
	CurrentUserUuid uuid.UUID `json:"current_user_uuid"`
}

func (q *Queries) SoftDeleteDirectMessage(ctx context.Context, arg SoftDeleteDirectMessageParams) (DirectMessage, error) {
	row := q.db.QueryRow(ctx, softDeleteDirectMessage, arg.DmID, arg.CurrentUserUuid)
	var i DirectMessage
	err := row.Scan(
		&i.DmID,
		&i.SenderID,
		&i.ReceiverID,
		&i.DmContent,
		&i.DmAttachments,
		&i.DmMessageType,
		&i.DmReadAt,
		&i.DmCreatedAt,
		&i.DmDeletedAt,
	)
	return i, err
}
