// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countRecords = `-- name: CountRecords :one
SELECT count(*)
FROM groups
WHERE (
    $1::bool IS NULL
    OR (group_deleted_at IS NOT NULL AND $1::bool IS TRUE)
    OR (group_deleted_at IS NULL AND $1::bool IS FALSE)
) AND (
    $2::TEXT IS NULL
    OR $2::TEXT = ''
    OR group_name ILIKE '%' || $2 || '%')
`

type CountRecordsParams struct {
	Deleted *bool  `json:"deleted"`
	Search  string `json:"search"`
}

func (q *Queries) CountRecords(ctx context.Context, arg CountRecordsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecords, arg.Deleted, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroup = `-- name: CreateGroup :one
WITH new_group AS (
    INSERT INTO groups (group_name)
    VALUES ($1)
    RETURNING group_id, group_uuid, group_name, group_created_at, group_updated_at, group_deleted_at
),
new_conversation AS (
    INSERT INTO conversations (conversation_type, reference_id)
    SELECT 2, ng.group_id
    FROM new_group ng
    RETURNING conversation_id, conversation_uuid, conversation_type, reference_id, last_message_id, last_message_at, conversation_created_at, conversation_updated_at
),
creator_user AS(
    SELECT user_id FROM users
    WHERE user_uuid =  $2::UUID
        AND user_deleted_at IS NULL
        AND user_status = 1
),
new_member AS(
    INSERT INTO group_members(group_id,user_id,member_role)
    SELECT  ng.group_id,cu.user_id,3
    FROM new_group ng,creator_user cu
    ON CONFLICT(group_id,user_id) WHERE left_at IS NULL DO NOTHING
    RETURNING group_member_id, group_id, user_id, member_role, jointed_at, left_at
),
new_participant AS(
    INSERT INTO conversation_participants (conversation_id, user_id)
    SELECT nc.conversation_id, nm.user_id
    FROM new_conversation nc, new_member nm
    ON CONFLICT (conversation_id,user_id) WHERE left_at IS NULL DO NOTHING
    RETURNING participant_id, conversation_id, user_id, last_read_message_id, last_read_at, is_muted, joined_at, left_at
)
SELECT
    ng.group_id,
    ng.group_uuid,
    ng.group_name,
    ng.group_created_at,
    ng.group_updated_at,
    nc.conversation_id,
    nc.conversation_uuid
FROM new_group ng
JOIN new_conversation nc ON true
`

type CreateGroupParams struct {
	GroupName string    `json:"group_name"`
	UserUuid  uuid.UUID `json:"user_uuid"`
}

type CreateGroupRow struct {
	GroupID          int32     `json:"group_id"`
	GroupUuid        uuid.UUID `json:"group_uuid"`
	GroupName        string    `json:"group_name"`
	GroupCreatedAt   time.Time `json:"group_created_at"`
	GroupUpdatedAt   time.Time `json:"group_updated_at"`
	ConversationID   int32     `json:"conversation_id"`
	ConversationUuid uuid.UUID `json:"conversation_uuid"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (CreateGroupRow, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.GroupName, arg.UserUuid)
	var i CreateGroupRow
	err := row.Scan(
		&i.GroupID,
		&i.GroupUuid,
		&i.GroupName,
		&i.GroupCreatedAt,
		&i.GroupUpdatedAt,
		&i.ConversationID,
		&i.ConversationUuid,
	)
	return i, err
}

const getAllGroups = `-- name: GetAllGroups :many
SELECT DISTINCT
    g.group_uuid,
    g.group_name,
    g.group_created_at,
    g.group_updated_at,
    gm.member_role,
    gm.jointed_at
FROM groups g
INNER JOIN group_members gm on g.group_id = gm.group_id
WHERE gm.user_id = (
    SELECT user_id FROM users WHERE user_uuid = $1::UUID
)
    AND gm.left_at IS NULL
    AND g.group_deleted_at IS NULL
    AND (
            $2 = ''
            OR to_tsvector('english', COALESCE(g.group_name, '')) @@
            plainto_tsquery('english', $2::TEXT)
        )
ORDER BY gm.jointed_at DESC
LIMIT $4 OFFSET $3
`

type GetAllGroupsParams struct {
	UserUuid  uuid.UUID   `json:"user_uuid"`
	Search    interface{} `json:"search"`
	Offsetarg int32       `json:"offsetarg"`
	Limitarg  int32       `json:"limitarg"`
}

type GetAllGroupsRow struct {
	GroupUuid      uuid.UUID `json:"group_uuid"`
	GroupName      string    `json:"group_name"`
	GroupCreatedAt time.Time `json:"group_created_at"`
	GroupUpdatedAt time.Time `json:"group_updated_at"`
	MemberRole     int32     `json:"member_role"`
	JointedAt      time.Time `json:"jointed_at"`
}

func (q *Queries) GetAllGroups(ctx context.Context, arg GetAllGroupsParams) ([]GetAllGroupsRow, error) {
	rows, err := q.db.Query(ctx, getAllGroups,
		arg.UserUuid,
		arg.Search,
		arg.Offsetarg,
		arg.Limitarg,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllGroupsRow{}
	for rows.Next() {
		var i GetAllGroupsRow
		if err := rows.Scan(
			&i.GroupUuid,
			&i.GroupName,
			&i.GroupCreatedAt,
			&i.GroupUpdatedAt,
			&i.MemberRole,
			&i.JointedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupByUUID = `-- name: GetGroupByUUID :one
SELECT
    g.group_uuid,
    g.group_name,
    g.group_created_at,
    g.group_updated_at,
    gm.member_role,
    gm.jointed_at
FROM groups g
INNER JOIN  group_members gm ON g.group_id = gm.group_id
WHERE gm.user_id = (
    SELECT user_id FROM users WHERE user_uuid = $1::UUID
)
    AND gm.left_at IS NULL
    AND g.group_deleted_at IS NULL
    AND g.group_uuid = $2::UUID
`

type GetGroupByUUIDParams struct {
	UserUuid  uuid.UUID `json:"user_uuid"`
	GroupUuid uuid.UUID `json:"group_uuid"`
}

type GetGroupByUUIDRow struct {
	GroupUuid      uuid.UUID `json:"group_uuid"`
	GroupName      string    `json:"group_name"`
	GroupCreatedAt time.Time `json:"group_created_at"`
	GroupUpdatedAt time.Time `json:"group_updated_at"`
	MemberRole     int32     `json:"member_role"`
	JointedAt      time.Time `json:"jointed_at"`
}

func (q *Queries) GetGroupByUUID(ctx context.Context, arg GetGroupByUUIDParams) (GetGroupByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getGroupByUUID, arg.UserUuid, arg.GroupUuid)
	var i GetGroupByUUIDRow
	err := row.Scan(
		&i.GroupUuid,
		&i.GroupName,
		&i.GroupCreatedAt,
		&i.GroupUpdatedAt,
		&i.MemberRole,
		&i.JointedAt,
	)
	return i, err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT member_role
FROM group_members
WHERE user_id = (SELECT user_id FROM users WHERE user_uuid = $1::UUID)
    AND group_id = (SELECT group_id FROM groups WHERE group_uuid = $2::UUID)
    AND left_at IS NULL
`

type GetMemberRoleParams struct {
	UserUuid  uuid.UUID `json:"user_uuid"`
	GroupUuid uuid.UUID `json:"group_uuid"`
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (int32, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.UserUuid, arg.GroupUuid)
	var member_role int32
	err := row.Scan(&member_role)
	return member_role, err
}

const hardDeleteGroup = `-- name: HardDeleteGroup :exec
DELETE FROM groups
WHERE group_uuid = $1::UUID and group_deleted_at IS NOT NULL
`

func (q *Queries) HardDeleteGroup(ctx context.Context, groupUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteGroup, groupUuid)
	return err
}

const leaveGroup = `-- name: LeaveGroup :exec
WITH uid AS (
        SELECT user_id FROM users
        WHERE user_uuid = $1::UUID
),
gid AS (
    SELECT group_id FROM groups
    WHERE group_uuid = $2::UUID
        AND group_deleted_at IS NULL
),
cid AS (
    SELECT conversation_id FROM conversations
    WHERE reference_id = (SELECT group_id FROM gid)
        AND conversation_type = 2   -- 2 = Group chat
),
leave_member AS (
    UPDATE group_members
    SET left_at = now()
    WHERE user_id = (SELECT user_id FROM uid)
        AND group_id = (SELECT group_id FROM gid)
        AND left_at IS NULL
)
UPDATE conversation_participants
SET left_at = now()
WHERE conversation_id = (SELECT conversation_id FROM cid)
  AND user_id = (SELECT user_id FROM uid)
  AND left_at IS NULL
`

type LeaveGroupParams struct {
	UserUuid  uuid.UUID `json:"user_uuid"`
	GroupUuid uuid.UUID `json:"group_uuid"`
}

func (q *Queries) LeaveGroup(ctx context.Context, arg LeaveGroupParams) error {
	_, err := q.db.Exec(ctx, leaveGroup, arg.UserUuid, arg.GroupUuid)
	return err
}

const softDeleteGroup = `-- name: SoftDeleteGroup :one
UPDATE groups
SET group_deleted_at = now()
WHERE group_uuid = $1::UUID
    AND group_deleted_at IS NULL
RETURNING group_id, group_uuid, group_name, group_created_at, group_updated_at, group_deleted_at
`

func (q *Queries) SoftDeleteGroup(ctx context.Context, groupUuid uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, softDeleteGroup, groupUuid)
	var i Group
	err := row.Scan(
		&i.GroupID,
		&i.GroupUuid,
		&i.GroupName,
		&i.GroupCreatedAt,
		&i.GroupUpdatedAt,
		&i.GroupDeletedAt,
	)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET group_name = $1
WHERE group_uuid = $2::UUID
    AND group_deleted_at IS NULL
RETURNING group_id, group_uuid, group_name, group_created_at, group_updated_at, group_deleted_at
`

type UpdateGroupParams struct {
	GroupName string    `json:"group_name"`
	GroupUuid uuid.UUID `json:"group_uuid"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup, arg.GroupName, arg.GroupUuid)
	var i Group
	err := row.Scan(
		&i.GroupID,
		&i.GroupUuid,
		&i.GroupName,
		&i.GroupCreatedAt,
		&i.GroupUpdatedAt,
		&i.GroupDeletedAt,
	)
	return i, err
}
