// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group_member.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addMemberToGroup = `-- name: AddMemberToGroup :exec
WITH target_group AS(
    SELECT group_id
    FROM groups
    WHERE group_uuid = $1::UUID
        AND group_deleted_at IS NULL
),
target_user AS(
    SELECT user_id
    FROM users
    WHERE user_uuid = $2::UUID
        AND user_deleted_at IS NULL
        AND user_status = 1
),
insert_member AS(
    INSERT INTO group_members (group_id, user_id, member_role)
    SELECT tg.group_id, tu.user_id, 1
    FROM target_group tg, target_user tu
    ON CONFLICT (group_id,user_id) WHERE left_at IS NULL DO UPDATE
        SET left_at = NULL,
            jointed_at = now(),
            member_role = EXCLUDED.member_role
    RETURNING group_member_id, user_id
),
target_conversation AS(
    SELECT conversation_id FROM conversations
    WHERE reference_id = (SELECT group_id FROM target_group)
        AND conversation_type = 2
)
INSERT INTO conversation_participants (conversation_id, user_id)
SELECT tc.conversation_id, im.user_id
FROM target_conversation tc, insert_member im
ON CONFLICT (conversation_id,user_id) WHERE left_at IS NULL DO UPDATE
    SET left_at = NULL,
        joined_at = now()
`

type AddMemberToGroupParams struct {
	GroupUuid uuid.UUID `json:"group_uuid"`
	UserUuid  uuid.UUID `json:"user_uuid"`
}

func (q *Queries) AddMemberToGroup(ctx context.Context, arg AddMemberToGroupParams) error {
	_, err := q.db.Exec(ctx, addMemberToGroup, arg.GroupUuid, arg.UserUuid)
	return err
}

const getGroupMembers = `-- name: GetGroupMembers :many
SELECT
    g.group_uuid,
    us.user_uuid,
    gm.member_role,
    gm.jointed_at
FROM group_members gm
INNER JOIN users us ON us.user_id = gm.user_id
INNER JOIN groups g ON g.group_id = gm.group_id
WHERE
    g.group_uuid = $1::UUID
    AND gm. left_at IS NULL
ORDER BY gm.jointed_at DESC
LIMIT $3 OFFSET $2
`

type GetGroupMembersParams struct {
	GroupUuid uuid.UUID `json:"group_uuid"`
	Offsetarg int32     `json:"offsetarg"`
	Limitarg  int32     `json:"limitarg"`
}

type GetGroupMembersRow struct {
	GroupUuid  uuid.UUID `json:"group_uuid"`
	UserUuid   uuid.UUID `json:"user_uuid"`
	MemberRole int32     `json:"member_role"`
	JointedAt  time.Time `json:"jointed_at"`
}

func (q *Queries) GetGroupMembers(ctx context.Context, arg GetGroupMembersParams) ([]GetGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, getGroupMembers, arg.GroupUuid, arg.Offsetarg, arg.Limitarg)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupMembersRow{}
	for rows.Next() {
		var i GetGroupMembersRow
		if err := rows.Scan(
			&i.GroupUuid,
			&i.UserUuid,
			&i.MemberRole,
			&i.JointedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemberInfo = `-- name: GetMemberInfo :one
SELECT
    us.user_uuid,
    us.user_email,
    g.group_uuid,
    gm.member_role,
    gm.jointed_at
FROM group_members gm
INNER JOIN users us ON us.user_id = gm.user_id
INNER JOIN groups g ON g.group_id = gm.group_id
WHERE
    us.user_uuid = $1::UUID
    AND g.group_uuid = $2::UUID
    AND gm.left_at IS NULL
`

type GetMemberInfoParams struct {
	UserUuid  uuid.UUID `json:"user_uuid"`
	GroupUuid uuid.UUID `json:"group_uuid"`
}

type GetMemberInfoRow struct {
	UserUuid   uuid.UUID `json:"user_uuid"`
	UserEmail  string    `json:"user_email"`
	GroupUuid  uuid.UUID `json:"group_uuid"`
	MemberRole int32     `json:"member_role"`
	JointedAt  time.Time `json:"jointed_at"`
}

func (q *Queries) GetMemberInfo(ctx context.Context, arg GetMemberInfoParams) (GetMemberInfoRow, error) {
	row := q.db.QueryRow(ctx, getMemberInfo, arg.UserUuid, arg.GroupUuid)
	var i GetMemberInfoRow
	err := row.Scan(
		&i.UserUuid,
		&i.UserEmail,
		&i.GroupUuid,
		&i.MemberRole,
		&i.JointedAt,
	)
	return i, err
}

const removeMember = `-- name: RemoveMember :one
UPDATE group_members
SET
    left_at = now()
WHERE
    group_id = (SELECT group_id FROM groups WHERE group_uuid = $1::UUID)
    AND user_id = (SELECT user_id FROM users WHERE user_uuid = $2::UUID)
    AND left_at IS NULL
RETURNING group_member_id, group_id, user_id, member_role, jointed_at, left_at
`

type RemoveMemberParams struct {
	GroupUuid uuid.UUID `json:"group_uuid"`
	UserUuid  uuid.UUID `json:"user_uuid"`
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, removeMember, arg.GroupUuid, arg.UserUuid)
	var i GroupMember
	err := row.Scan(
		&i.GroupMemberID,
		&i.GroupID,
		&i.UserID,
		&i.MemberRole,
		&i.JointedAt,
		&i.LeftAt,
	)
	return i, err
}

const updateMemberRole = `-- name: UpdateMemberRole :one
UPDATE group_members
SET
    member_role = $1
WHERE
    group_id = (SELECT group_id FROM groups WHERE group_uuid = $2::UUID)
    AND user_id = (SELECT user_id FROM users WHERE user_uuid = $3::UUID)
    AND left_at IS NULL
RETURNING group_member_id, group_id, user_id, member_role, jointed_at, left_at
`

type UpdateMemberRoleParams struct {
	MemberRole int32     `json:"member_role"`
	GroupUuid  uuid.UUID `json:"group_uuid"`
	UserUuid   uuid.UUID `json:"user_uuid"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, updateMemberRole, arg.MemberRole, arg.GroupUuid, arg.UserUuid)
	var i GroupMember
	err := row.Scan(
		&i.GroupMemberID,
		&i.GroupID,
		&i.UserID,
		&i.MemberRole,
		&i.JointedAt,
		&i.LeftAt,
	)
	return i, err
}
