// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups(
    group_name
) VALUES ($1)
RETURNING group_id, group_uuid, group_name, group_created_at, group_updated_at, group_deleted_at
`

func (q *Queries) CreateGroup(ctx context.Context, groupName string) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, groupName)
	var i Group
	err := row.Scan(
		&i.GroupID,
		&i.GroupUuid,
		&i.GroupName,
		&i.GroupCreatedAt,
		&i.GroupUpdatedAt,
		&i.GroupDeletedAt,
	)
	return i, err
}

const getAllGroups = `-- name: GetAllGroups :many
SELECT DISTINCT
    g.group_uuid,
    g.group_name,
    g.group_created_at,
    g.group_updated_at,
    gm.member_role,
    gm.jointed_at
FROM groups g
INNER JOIN group_members gm on g.group_id = gm.group_id
WHERE gm.member_id = (
    SELECT user_id FROM users WHERE user_uuid = $1::UUID
)
    AND gm.left_at IS NULL
    AND g.group_deleted_at IS NULL
ORDER BY gm.jointed_at DESC
LIMIT $3 OFFSET $2
`

type GetAllGroupsParams struct {
	UserUuid  uuid.UUID `json:"user_uuid"`
	Offsetarg int32     `json:"offsetarg"`
	Limitarg  int32     `json:"limitarg"`
}

type GetAllGroupsRow struct {
	GroupUuid      uuid.UUID `json:"group_uuid"`
	GroupName      string    `json:"group_name"`
	GroupCreatedAt time.Time `json:"group_created_at"`
	GroupUpdatedAt time.Time `json:"group_updated_at"`
	MemberRole     int32     `json:"member_role"`
	JointedAt      time.Time `json:"jointed_at"`
}

func (q *Queries) GetAllGroups(ctx context.Context, arg GetAllGroupsParams) ([]GetAllGroupsRow, error) {
	rows, err := q.db.Query(ctx, getAllGroups, arg.UserUuid, arg.Offsetarg, arg.Limitarg)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllGroupsRow{}
	for rows.Next() {
		var i GetAllGroupsRow
		if err := rows.Scan(
			&i.GroupUuid,
			&i.GroupName,
			&i.GroupCreatedAt,
			&i.GroupUpdatedAt,
			&i.MemberRole,
			&i.JointedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupByUUID = `-- name: GetGroupByUUID :one
SELECT
    g.group_uuid,
    g.group_name,
    g.group_created_at,
    g.group_updated_at,
    gm.member_role,
    gm.jointed_at
FROM groups g
INNER JOIN  group_members gm ON g.group_id = gm.group_id
WHERE gm.member_id = (
    SELECT user_id FROM users WHERE user_uuid = $1::UUID
)
    AND gm.left_at IS NULL
    AND g.group_deleted_at IS NULL
    AND g.group_uuid = $2::UUID
`

type GetGroupByUUIDParams struct {
	UserUuid  uuid.UUID `json:"user_uuid"`
	GroupUuid uuid.UUID `json:"group_uuid"`
}

type GetGroupByUUIDRow struct {
	GroupUuid      uuid.UUID `json:"group_uuid"`
	GroupName      string    `json:"group_name"`
	GroupCreatedAt time.Time `json:"group_created_at"`
	GroupUpdatedAt time.Time `json:"group_updated_at"`
	MemberRole     int32     `json:"member_role"`
	JointedAt      time.Time `json:"jointed_at"`
}

func (q *Queries) GetGroupByUUID(ctx context.Context, arg GetGroupByUUIDParams) (GetGroupByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getGroupByUUID, arg.UserUuid, arg.GroupUuid)
	var i GetGroupByUUIDRow
	err := row.Scan(
		&i.GroupUuid,
		&i.GroupName,
		&i.GroupCreatedAt,
		&i.GroupUpdatedAt,
		&i.MemberRole,
		&i.JointedAt,
	)
	return i, err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT member_role
FROM group_members
WHERE member_id = (SELECT user_id FROM users WHERE user_uuid = $1::UUID)
    AND group_id = (SELECT group_id FROM groups WHERE group_uuid = $2::UUID)
    AND left_at IS NULL
`

type GetMemberRoleParams struct {
	UserUuid  uuid.UUID `json:"user_uuid"`
	GroupUuid uuid.UUID `json:"group_uuid"`
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (int32, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.UserUuid, arg.GroupUuid)
	var member_role int32
	err := row.Scan(&member_role)
	return member_role, err
}

const hardDeleteGroup = `-- name: HardDeleteGroup :exec
DELETE FROM groups
WHERE group_uuid = $1::UUID and group_deleted_at IS NULL
`

func (q *Queries) HardDeleteGroup(ctx context.Context, groupUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteGroup, groupUuid)
	return err
}

const leaveGroup = `-- name: LeaveGroup :exec
UPDATE group_members
SET left_at = now()
WHERE member_id = (SELECT user_id FROM users WHERE user_uuid = $1::UUID)
    AND group_id = (SELECT group_id FROM groups WHERE group_uuid = $2::UUID)
    AND left_at IS NULL
`

type LeaveGroupParams struct {
	UserUuid  uuid.UUID `json:"user_uuid"`
	GroupUuid uuid.UUID `json:"group_uuid"`
}

func (q *Queries) LeaveGroup(ctx context.Context, arg LeaveGroupParams) error {
	_, err := q.db.Exec(ctx, leaveGroup, arg.UserUuid, arg.GroupUuid)
	return err
}

const softDeleteGroup = `-- name: SoftDeleteGroup :one
UPDATE groups
SET group_deleted_at = now()
WHERE group_uuid = $1::UUID
    AND group_deleted_at IS NULL
RETURNING group_id, group_uuid, group_name, group_created_at, group_updated_at, group_deleted_at
`

func (q *Queries) SoftDeleteGroup(ctx context.Context, groupUuid uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, softDeleteGroup, groupUuid)
	var i Group
	err := row.Scan(
		&i.GroupID,
		&i.GroupUuid,
		&i.GroupName,
		&i.GroupCreatedAt,
		&i.GroupUpdatedAt,
		&i.GroupDeletedAt,
	)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET group_name = $1
WHERE group_uuid = $2::UUID
    AND group_deleted_at IS NULL
RETURNING group_id, group_uuid, group_name, group_created_at, group_updated_at, group_deleted_at
`

type UpdateGroupParams struct {
	GroupName string    `json:"group_name"`
	GroupUuid uuid.UUID `json:"group_uuid"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup, arg.GroupName, arg.GroupUuid)
	var i Group
	err := row.Scan(
		&i.GroupID,
		&i.GroupUuid,
		&i.GroupName,
		&i.GroupCreatedAt,
		&i.GroupUpdatedAt,
		&i.GroupDeletedAt,
	)
	return i, err
}
