// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const editMessage = `-- name: EditMessage :one
UPDATE messages
SET
    message_content = $1
WHERE
    group_id = (SELECT group_id FROM groups WHERE group_uuid = $2::UUID)
    AND sender_id = (SELECT user_id FROM users WHERE user_uuid = $3::UUID)
    AND EXISTS(
        SELECT 1
        FROM group_members gm
        INNER JOIN groups g ON g.group_id = gm.group_id
        INNER JOIN users u ON u.user_id = sender_id
        WHERE
            gm.left_at IS NULL
    )
RETURNING message_id, sender_id, group_id, message_content, attachments, message_type, reply_to, message_created_at, message_deleted_at
`

type EditMessageParams struct {
	MessageContent string    `json:"message_content"`
	GroupUuid      uuid.UUID `json:"group_uuid"`
	UserUuid       uuid.UUID `json:"user_uuid"`
}

func (q *Queries) EditMessage(ctx context.Context, arg EditMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, editMessage, arg.MessageContent, arg.GroupUuid, arg.UserUuid)
	var i Message
	err := row.Scan(
		&i.MessageID,
		&i.SenderID,
		&i.GroupID,
		&i.MessageContent,
		&i.Attachments,
		&i.MessageType,
		&i.ReplyTo,
		&i.MessageCreatedAt,
		&i.MessageDeletedAt,
	)
	return i, err
}

const searchMessageInGroup = `-- name: SearchMessageInGroup :many
SELECT
    u.user_uuid,
    ms.message_content,
    ms.attachments,
    ms.message_type,
    ms.reply_to,
    ms.message_created_at
FROM messages ms
INNER JOIN groups g ON g.group_id = ms.group_id
INNER JOIN users u ON u.user_id = ms.sender_id
WHERE
    g.group_uuid = $1::UUID
    AND EXISTS (
        SELECT 1 FROM group_members gm
        WHERE gm.group_id = g.group_id
            AND gm.member_id = u.user_id
            AND gm.left_at IS NULL
    )
    AND to_tsvector('english', COALESCE(ms.message_content, '')) @@
        plainto_tsquery('english', $2::TEXT)
ORDER BY ms.message_created_at DESC
LIMIT $4 OFFSET $3
`

type SearchMessageInGroupParams struct {
	GroupUuid uuid.UUID `json:"group_uuid"`
	Search    string    `json:"search"`
	Offsetarg int32     `json:"offsetarg"`
	Limitarg  int32     `json:"limitarg"`
}

type SearchMessageInGroupRow struct {
	UserUuid         uuid.UUID `json:"user_uuid"`
	MessageContent   string    `json:"message_content"`
	Attachments      []byte    `json:"attachments"`
	MessageType      int32     `json:"message_type"`
	ReplyTo          *int32    `json:"reply_to"`
	MessageCreatedAt time.Time `json:"message_created_at"`
}

func (q *Queries) SearchMessageInGroup(ctx context.Context, arg SearchMessageInGroupParams) ([]SearchMessageInGroupRow, error) {
	rows, err := q.db.Query(ctx, searchMessageInGroup,
		arg.GroupUuid,
		arg.Search,
		arg.Offsetarg,
		arg.Limitarg,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMessageInGroupRow{}
	for rows.Next() {
		var i SearchMessageInGroupRow
		if err := rows.Scan(
			&i.UserUuid,
			&i.MessageContent,
			&i.Attachments,
			&i.MessageType,
			&i.ReplyTo,
			&i.MessageCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sendMessageToGroup = `-- name: SendMessageToGroup :one
INSERT INTO messages (sender_id, group_id, message_content, attachments, message_type, reply_to)
SELECT
    u.user_id,
    g.group_id,
    $1::TEXT,
    $2::JSONB,
    COALESCE($3::INT, 1),
    $4::INT
FROM users u, groups g
WHERE u.user_uuid = $5::UUID
  AND g.group_uuid = $6::UUID
  AND EXISTS (
      SELECT 1 FROM group_members gm
      WHERE gm.group_id = g.group_id
        AND gm.member_id = u.user_id
        AND gm.left_at IS NULL
  )
  AND g.group_deleted_at IS NULL
RETURNING
    message_id,
    sender_id,
    group_id,
    message_content,
    attachments,
    message_type,
    reply_to,
    message_created_at
`

type SendMessageToGroupParams struct {
	MessageContent string          `json:"message_content"`
	Attachments    json.RawMessage `json:"attachments"`
	MessageType    int32           `json:"message_type"`
	ReplyTo        int32           `json:"reply_to"`
	SenderUuid     uuid.UUID       `json:"sender_uuid"`
	GroupUuid      uuid.UUID       `json:"group_uuid"`
}

type SendMessageToGroupRow struct {
	MessageID        int32     `json:"message_id"`
	SenderID         int32     `json:"sender_id"`
	GroupID          int32     `json:"group_id"`
	MessageContent   string    `json:"message_content"`
	Attachments      []byte    `json:"attachments"`
	MessageType      int32     `json:"message_type"`
	ReplyTo          *int32    `json:"reply_to"`
	MessageCreatedAt time.Time `json:"message_created_at"`
}

func (q *Queries) SendMessageToGroup(ctx context.Context, arg SendMessageToGroupParams) (SendMessageToGroupRow, error) {
	row := q.db.QueryRow(ctx, sendMessageToGroup,
		arg.MessageContent,
		arg.Attachments,
		arg.MessageType,
		arg.ReplyTo,
		arg.SenderUuid,
		arg.GroupUuid,
	)
	var i SendMessageToGroupRow
	err := row.Scan(
		&i.MessageID,
		&i.SenderID,
		&i.GroupID,
		&i.MessageContent,
		&i.Attachments,
		&i.MessageType,
		&i.ReplyTo,
		&i.MessageCreatedAt,
	)
	return i, err
}

const softDeleteMessage = `-- name: SoftDeleteMessage :one
UPDATE messages
SET message_deleted_at = now()
WHERE message_id = $1::INT
  AND sender_id = (SELECT user_id FROM users WHERE user_uuid = $2::UUID)
  AND group_id = (SELECT group_id FROM groups WHERE group_uuid = $3::UUID)
  AND EXISTS (
      SELECT 1 FROM group_members gm
      WHERE gm.group_id = messages.group_id
        AND gm.member_id = messages.sender_id
        AND gm.left_at IS NULL
  )
RETURNING message_id, sender_id, group_id, message_content, attachments, message_type, reply_to, message_created_at, message_deleted_at
`

type SoftDeleteMessageParams struct {
	MessageID int32     `json:"message_id"`
	UserUuid  uuid.UUID `json:"user_uuid"`
	GroupUuid uuid.UUID `json:"group_uuid"`
}

func (q *Queries) SoftDeleteMessage(ctx context.Context, arg SoftDeleteMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, softDeleteMessage, arg.MessageID, arg.UserUuid, arg.GroupUuid)
	var i Message
	err := row.Scan(
		&i.MessageID,
		&i.SenderID,
		&i.GroupID,
		&i.MessageContent,
		&i.Attachments,
		&i.MessageType,
		&i.ReplyTo,
		&i.MessageCreatedAt,
		&i.MessageDeletedAt,
	)
	return i, err
}
