// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddMemberToGroup(ctx context.Context, arg AddMemberToGroupParams) error
	AddParticipantToConversation(ctx context.Context, arg AddParticipantToConversationParams) error
	CountRecords(ctx context.Context, arg CountRecordsParams) (int64, error)
	CreateDMConversation(ctx context.Context) (int32, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (CreateGroupRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	EditMessage(ctx context.Context, arg EditMessageParams) (Message, error)
	FindDMConversation(ctx context.Context, arg FindDMConversationParams) (int32, error)
	FindUserByEmail(ctx context.Context, userEmail string) (User, error)
	FindUserByUUID(ctx context.Context, userUuid uuid.UUID) (User, error)
	GetAllGroups(ctx context.Context, arg GetAllGroupsParams) ([]GetAllGroupsRow, error)
	GetDMConversation(ctx context.Context, curUserID int32) ([]GetDMConversationRow, error)
	GetGroupByUUID(ctx context.Context, arg GetGroupByUUIDParams) (GetGroupByUUIDRow, error)
	GetGroupConversation(ctx context.Context, curUserID int32) ([]GetGroupConversationRow, error)
	GetGroupMembers(ctx context.Context, arg GetGroupMembersParams) ([]GetGroupMembersRow, error)
	GetMemberInfo(ctx context.Context, arg GetMemberInfoParams) (GetMemberInfoRow, error)
	GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (int32, error)
	GetMessages(ctx context.Context, arg GetMessagesParams) ([]GetMessagesRow, error)
	HardDelete(ctx context.Context, userUuid uuid.UUID) (User, error)
	HardDeleteConversation(ctx context.Context, groupUuid uuid.UUID) error
	HardDeleteGroup(ctx context.Context, groupUuid uuid.UUID) error
	LeaveConversation(ctx context.Context, arg LeaveConversationParams) error
	LeaveGroup(ctx context.Context, arg LeaveGroupParams) error
	RemoveMember(ctx context.Context, arg RemoveMemberParams) (GroupMember, error)
	RestoreUser(ctx context.Context, userUuid uuid.UUID) (User, error)
	SearchMessageInGroup(ctx context.Context, arg SearchMessageInGroupParams) ([]SearchMessageInGroupRow, error)
	SendMessage(ctx context.Context, arg SendMessageParams) (int32, error)
	SoftDelete(ctx context.Context, userUuid uuid.UUID) (User, error)
	SoftDeleteGroup(ctx context.Context, groupUuid uuid.UUID) (Group, error)
	SoftDeleteMessage(ctx context.Context, arg SoftDeleteMessageParams) (Message, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (GroupMember, error)
	ValidateReply(ctx context.Context, arg ValidateReplyParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
