// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddMemberToGroup(ctx context.Context, arg AddMemberToGroupParams) (GroupMember, error)
	CreateGroup(ctx context.Context, groupName string) (Group, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	EditDirectMessage(ctx context.Context, arg EditDirectMessageParams) (DirectMessage, error)
	EditMessage(ctx context.Context, arg EditMessageParams) (Message, error)
	FindUserByEmail(ctx context.Context, userEmail string) (User, error)
	FindUserByUUID(ctx context.Context, userUuid uuid.UUID) (User, error)
	GetAllGroups(ctx context.Context, arg GetAllGroupsParams) ([]GetAllGroupsRow, error)
	GetDirectMessageWithUser(ctx context.Context, arg GetDirectMessageWithUserParams) ([]GetDirectMessageWithUserRow, error)
	GetDirectMessagesConversations(ctx context.Context, arg GetDirectMessagesConversationsParams) ([]GetDirectMessagesConversationsRow, error)
	GetGroupByUUID(ctx context.Context, arg GetGroupByUUIDParams) (GetGroupByUUIDRow, error)
	GetGroupMembers(ctx context.Context, arg GetGroupMembersParams) ([]GetGroupMembersRow, error)
	GetMemberInfo(ctx context.Context, arg GetMemberInfoParams) (GetMemberInfoRow, error)
	GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (int32, error)
	GetUnreadDM(ctx context.Context, currentUserUuid uuid.UUID) (GetUnreadDMRow, error)
	HardDelete(ctx context.Context, userUuid uuid.UUID) (User, error)
	HardDeleteGroup(ctx context.Context, groupUuid uuid.UUID) error
	LeaveGroup(ctx context.Context, arg LeaveGroupParams) error
	ReadAllDirectMessages(ctx context.Context, arg ReadAllDirectMessagesParams) (int64, error)
	ReadDirectMessage(ctx context.Context, arg ReadDirectMessageParams) (DirectMessage, error)
	RemoveMember(ctx context.Context, arg RemoveMemberParams) (GroupMember, error)
	RestoreUser(ctx context.Context, userUuid uuid.UUID) (User, error)
	SearchDirectMessagesWithUser(ctx context.Context, arg SearchDirectMessagesWithUserParams) ([]SearchDirectMessagesWithUserRow, error)
	SearchMessageInGroup(ctx context.Context, arg SearchMessageInGroupParams) ([]SearchMessageInGroupRow, error)
	SendMessageToGroup(ctx context.Context, arg SendMessageToGroupParams) (SendMessageToGroupRow, error)
	SentDirectMessages(ctx context.Context, arg SentDirectMessagesParams) (DirectMessage, error)
	SoftDelete(ctx context.Context, userUuid uuid.UUID) (User, error)
	SoftDeleteDirectMessage(ctx context.Context, arg SoftDeleteDirectMessageParams) (DirectMessage, error)
	SoftDeleteGroup(ctx context.Context, groupUuid uuid.UUID) (Group, error)
	SoftDeleteMessage(ctx context.Context, arg SoftDeleteMessageParams) (Message, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (GroupMember, error)
}

var _ Querier = (*Queries)(nil)
