// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserID       int32     `json:"user_id"`
	UserUuid     uuid.UUID `json:"user_uuid"`
	UserEmail    string    `json:"user_email"`
	UserPassword string    `json:"user_password"`
	// User Role: 1 - User, 2 - Adminstator
	UserRole int32 `json:"user_role"`
	// User Status: 1 - Active, 2 - Inactive, 3 - Banned
	UserStatus    int32     `json:"user_status"`
	UserCreatedAt time.Time `json:"user_created_at"`
	UserUpdatedAt time.Time `json:"user_updated_at"`
	// Soft delete timestamp: NULL means not deleted
	UserDeletedAt pgtype.Timestamptz `json:"user_deleted_at"`
}
