// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FindUserByEmail(ctx context.Context, userEmail string) (User, error)
}

var _ Querier = (*Queries)(nil)
